# File containing all commands.
commands = {'VA1': '"Attack left lane!"',
 'VA2': '"Attack middle lane!"',
 'VA3': '"Attack right lane!"',
 'VAA': '"Attack!"',
 'VAF': '"Attack Fire Giant!"',
 'VAG': '"Attack the Gold Fury!"',
 'VAM': '"Attack the Titan!"',
 'VAT1': 'Attack left tower/phoenix',
 'VAT2': 'Attack middle tower/phoenix',
 'VAT3': 'Attack right tower/phoenix',
 'VB1': '"Enemies in left lane!"',
 'VB2': '"Enemies in middle lane!"',
 'VB3': '"Enemies in right lane!"',
 'VBA': '"Enemy ultimate incoming!"',
 'VBB': '"Enemies have returned to base."',
 'VBD': '"Enemy ultimate down!"',
 'VBE': '"Enemies behind us!"',
 'VBF': '"Enemies at the Fire Giant!"',
 'VBG': '"Enemies at the Gold Fury!"',
 'VBJ1': '"Enemies in the Left Jungle!"',
 'VBJ3': '"Enemies in the right jungle!"',
 'VBJJ': '"Enemies in the jungle!"',
 'VBM': '"Enemies at our Titan!"',
 'VBS': '"Enemy spotted!"',
 'VC1': '"Be careful left!"',
 'VC2': '"Be careful middle!"',
 'VC3': '"Be careful right!"',
 'VCB': '"Return to base!"',
 'VCC': '"Be careful!"',
 'VCJ': '"Be careful in the jungle!"',
 'VD1': '"Defend left lane!"',
 'VD2': '"Defend middle lane!"',
 'VD3': '"Defend right lane!"',
 'VDD': '"Defend!"',
 'VDF': '"Defend the Fire Giant!"',
 'VDG': '"Defend the Gold Fury!"',
 'VDM': '"Defend the Titan!"',
 'VEA': 'Awesome',
 'VEG': 'Greatest',
 'VEJ': 'Joke',
 'VEL': 'Laugh',
 'VER': 'You rock!',
 'VET': 'Taunt!',
 'VEW': 'Woohoo!',
 'VF1': '"Enemy missing left!"',
 'VF2': '"Enemy missing middle!"',
 'VF3': '"Enemy missing right!"',
 'VFF': '"Enemy missing!"',
 'VG1': '"Gank left lane!"',
 'VG2': '"Gank middle lane!"',
 'VG3': '"Gank right lane!"',
 'VGG': '"Gank!"',
 'VH1': '"Help left lane!"',
 'VH2': '"Help middle lane!"',
 'VH3': '"Help right lane!"',
 'VHH': '"Help!"',
 'VHS': '"Need Healing!"',
 'VI1': '"Enemies incoming left!"',
 'VI2': '"Enemies incoming middle!"',
 'VI3': '"Enemies incoming right!"',
 'VII': '"Enemies incoming!"',
 'VQ1': '"Ward Left!"',
 'VQ2': '"Ward middle!"',
 'VQ3': '"Ward Right!"',
 'VQF': '"Ward Fire Giant!"',
 'VQG': '"Ward Gold Fury!"',
 'VQN': '"Need Wards!"',
 'VQQ': '"Ward Here!"',
 'VR1': '"Retreat left lane!"',
 'VR2': '"Retreat middle lane!"',
 'VR3': '"Retreat right lane!"',
 'VRJ': '"Retreat from the Jungle!"',
 'VRR': '"Retreat!"',
 'VRS': '"Save yourself!"',
 'VSA1': '"I\'ll Attack left lane!"',
 'VSA2': '"I\'ll Attack middle lane!"',
 'VSA3': '"I\'ll Attack right lane!"',
 'VSAA': '"I\'ll Attack!"',
 'VSAF': '"I\'ll Attack Fire Giant!"',
 'VSAG': '"I\'ll Attack the Gold Fury!"',
 'VSAM': '"I\'ll Attack the Titan!"',
 'VSBB': '"I\'m going for jungle buff!"',
 'VSBN': '"I need the jungle buff."',
 'VSBT': '"Take this jungle buff."',
 'VSD1': '"I\'ll defend left lane!"',
 'VSD2': '"I\'ll defend middle lane!"',
 'VSD3': '"I\'ll defend right lane!"',
 'VSDD': '"I\'ll defend!"',
 'VSDF': '"I\'ll defend the Fire Giant!"',
 'VSDG': '"I\'ll defend the Gold Fury!"',
 'VSDM': '"I\'ll defend the Titan!"',
 'VSG1': '"I\'ll gank left lane!"',
 'VSG2': '"I\'ll gank middle lane!"',
 'VSG3': '"I\'ll gank right lane!"',
 'VSGG': '"I\'ll gank!"',
 'VSO': '"I\'m on it!"',
 'VSQ1': '"I will ward left!"',
 'VSQ2': '"I will ward middle!"',
 'VSQ3': '"I will ward right!"',
 'VSQQ': '"I will ward!"',
 'VSR': '"Falling back!"',
 'VSS': '"I\'m building Stacks!"',
 'VST1': '"I\'m returning left lane!"',
 'VST2': '"I\'m returning middle lane!"',
 'VST3': '"I\'m returning right lane!"',
 'VSTB': '"I\'m returning to base!"',
 'VSTT': '"I have returned!"',
 'VT1': '"Enemies have returned left!"',
 'VT2': '"Enemies have returned middle!"',
 'VT3': '"Enemies have returned right!"',
 'VTT': '"Enemies have returned!"',
 'VVA': '"Ok!"',
 'VVB': '"Be right back!"',
 'VVC': '"Completed!"',
 'VVGB': '"Bye!"',
 'VVGF': '"Have fun!"',
 'VVGG': '"Good game!"',
 'VVGH': '"Hi!"',
 'VVGL': '"Good luck!"',
 'VVGN': '"Nice Job!"',
 'VVGO': '"Oops!"',
 'VVGQ': '"Quiet!"',
 'VVGR': '"No Problem!"',
 'VVGS': '"Curses!"',
 'VVGT': '"That\'s too bad!"',
 'VVGW': '"You\'re welcome!"',
 'VVK': '"Stepping away for a moment."',
 'VVM': '"Out of mana!"',
 'VVN': '"No!"',
 'VVP': '"Please?"',
 'VVS': '"Sorry!"',
 'VVT': '"Thanks!"',
 'VVVA': '"Set up an ambush here!"',
 'VVVB': '"Behind us!"',
 'VVVC': '"Chase the enemy!"',
 'VVVD': '"Ultimate is down!"',
 'VVVE': '"On my way!"',
 'VVVF': '"Follow me!"',
 'VVVG': '"Group up!"',
 'VVVJ': '"Going into the jungle!"',
 'VVVP': '"Split push!"',
 'VVVR': '"Ultimate is ready!"',
 'VVVS': '"Stay here!"',
 'VVVT': '"It\'s a trap!"',
 'VVVW': '"Place a Ward for teleport!"',
 'VVVX': '"Spread Out!"',
 'VVW': '"Wait!"',
 'VVX': '"Cancel that!"',
 'VVY': '"Yes!"'}

headlines = ['List of all Voice Commands',
 'A - Attack',
 'B - Enemy',
 'C - Careful',
 'D - Defend',
 'E - Emotes',
 'F - MIA',
 'G - Gank',
 'H - Help',
 'I - Incoming',
 'Q - Ward',
 'R - Retreat',
 'S - Self',
 'T - Returned',
 'V - Other']
 # Left out social emotes